#!/usr/bin/env python
# coding: utf-8

# In[15]:


from sklearn.cluster import KMeans
from sklearn import preprocessing
import pandas as pd

#数据加载
data = pd.read_csv('D:\Data Engine\Python\Lesson 3\car_data.csv')
train_x = data [["人均GDP","城镇人口比重","交通工具消费价格指数","百户拥有汽车量"]]

# 规范化到[0,1]空间
min_max_scaler=preprocessing.MinMaxScaler()
train_x=min_max_scaler.fit_transform(train_x)

# 使用kmeans进行聚类
kmeans = KMeans(n_clusters=3)
#训练
kmeans.fit(train_x)
#预测
predict_y = kmeans.predict(train_x)
#合并聚类结果，插入原数据
result = pd.concat((data,pd.DataFrame(predict_y)),axis=1)
result.rename({0:u'聚类结果'},axis=1,inplace=True)
print(result)

#将结果导入csv文件中
result.to_csv('D:\Data Engine\Python\Lesson 3\car_cluster_result.csv',index=False)

